import "./style.css";
import { compileMachine } from "./compiler/compiler.js";
import { diagnosticFromError, route, type Diagnostic } from "./app/ui-state.js";
import { AGENT_APPROVAL_SOURCE } from "./examples/agentApproval.js";
import { browserDeployment, browserLock, readLiveStep, readOnlyQuote, weiToOkb, type LiveStepResult, type ReadOnlyQuote } from "./app/protocol.js";
import { EXAMPLES, compileExample, inputBytes, localStep, stateName, type CompiledExample, type ExampleKey } from "./app/model.js";
import { readSessions, sessionKey, upsertSession, type BrowserSession } from "./app/session.js";
import { abbreviatedAccount, bindProviderEvents, discoverOkxProvider, installEip6963Discovery, readWallet, requestOkxAccounts, type WalletState } from "./app/wallet.js";
import type { CompiledMachine } from "./compiler/types.js";

const app = typeof document === "undefined" ? undefined : document.querySelector<HTMLElement>("#app");

interface UiState {
  key: ExampleKey; source: string; compiled?: CompiledExample; diagnostics: Diagnostic[]; compiling: boolean;
  selectedState: number; inputs: Record<string, boolean>; live?: LiveStepResult; liveError?: string; liveLoading: boolean;
  quote?: ReadOnlyQuote; quoteError?: string; quoteLoading: boolean; restored?: BrowserSession;
  wallet: WalletState;
}

const state: UiState = { key: "agent", source: AGENT_APPROVAL_SOURCE.trim(), diagnostics: [], compiling: true, selectedState: 0, inputs: {}, liveLoading: false, quoteLoading: false, wallet: { status: "unavailable" } };

if (app) void boot(app);

function esc(value: string): string { return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] as string); }
function shortHash(value: string): string { return `${value.slice(0, 10)}…${value.slice(-8)}`; }
function nav(active: string): string { return `<header class="topbar"><a class="brand" href="#/"><span class="brand-mark">GX</span><span>GateX</span></a><nav aria-label="Primary"><a class="nav-link ${active === "/" ? "active" : ""}" href="#/">Overview</a><a class="nav-link ${active === "/workspace" ? "active" : ""}" href="#/workspace">Workspace</a><a class="nav-link ${active === "/evidence" ? "active" : ""}" href="#/evidence">Evidence</a></nav><span class="network-pill"><span class="live-dot"></span>X Layer / 196</span></header>`; }
function badge(label: string, tone: "green" | "amber" | "blue" | "muted" = "muted"): string { return `<span class="badge ${tone}">${esc(label)}</span>`; }
function proofStat(value: string, label: string): string { return `<div class="proof-stat"><strong>${esc(value)}</strong><span>${esc(label)}</span></div>`; }
function machineSummary(compiled: CompiledExample): string { const machine = compiled.compiled.machine; return `<div class="summary-grid">${proofStat(String(compiled.compiled.nandCount), "NAND gates")}${proofStat(String(compiled.compiled.latchCount), "LATCH records")}${proofStat(String(machine.states.length), "states")}${proofStat(`${machine.inputs.length} / ${machine.outputs.length}`, "inputs / outputs")}</div>`; }
function stateDiagram(compiled: CompiledMachine): string { const states = compiled.machine.states.map((item, index) => `<span class="state-node ${item.terminal ? "terminal" : ""}">${esc(item.name)}${item.terminal ? " <small>terminal</small>" : ""}<em>${index}</em></span>`).join(`<span class="state-arrow">→</span>`); return `<div class="state-diagram" aria-label="State diagram">${states}</div><p class="muted">Reset input: <code>${esc(compiled.machine.resetInput)}</code>. Reset has priority and clears transition-pulse outputs. Terminal states hold until reset.</p>`; }
function statusRow(label: string, status: "passed" | "pending" | "warning" | "stale", detail: string): string { const title = status === "passed" ? "Passed" : status === "warning" ? "Review" : status === "stale" ? "Stale" : "Pending"; return `<div class="status-row"><span class="status-icon ${status}">${status === "passed" ? "✓" : status === "warning" ? "!" : "•"}</span><span><strong>${esc(label)}</strong><small>${esc(detail)}</small></span><span class="status-word ${status}">${title}</span></div>`; }
function formatBytes(bytes: Uint8Array): string { return `0x${Array.from(bytes, (value) => value.toString(16).padStart(2, "0")).join("")}`; }
async function compileCurrent(): Promise<void> {
  const source = state.source; state.compiling = true; state.diagnostics = []; render();
  try { state.compiled = await compileExample(state.key, source); state.selectedState = state.compiled.compiled.machine.stateIndex.get(state.compiled.compiled.machine.initialState) ?? 0; state.inputs = Object.fromEntries(state.compiled.compiled.machine.inputs.map((input) => [input.name, false])); state.live = undefined; state.liveError = undefined; const restored = readSessions().find((candidate) => sessionKey(candidate) === sessionKey({ artifactDigest: state.compiled?.compiled.hash ?? "", chainId: browserLock.chainId, processor: browserDeployment.processor, circuitId: state.compiled?.definition.circuitId ?? "" }) && candidate.sourceDigest === state.compiled?.sourceDigest); state.restored = restored === undefined ? undefined : { ...restored, history: restored.history.map((entry) => ({ ...entry, origin: "LOCAL SIMULATION" as const })) }; }
  catch (error) { state.compiled = undefined; state.diagnostics = diagnosticFromError(error, source); }
  finally { state.compiling = false; render(); }
}
function sourceCard(source: string): string { return `<pre class="code-block"><code>${esc(source)}</code></pre>`; }

function landing(): string { const compiled = state.key === "agent" ? state.compiled : undefined; return `${nav("/")}<main class="page landing"><section class="hero"><div class="eyebrow">VERIFIED CIRCUIT COMPILER <span>•</span> X LAYER / 196</div><h1>State machines,<br><span>made tangible.</span></h1><p class="hero-copy">GateX turns human-readable application state machines into verified TapeOut NAND/LATCH circuits on X Layer.</p><div class="hero-actions"><a class="button primary" href="#/workspace">Open workspace <span>↗</span></a><a class="text-link" href="#/evidence">View evidence</a></div><div class="hero-proof"><span class="pulse-check">✓</span><span><strong>AgentApproval</strong> is the flagship proof</span><span class="divider"></span><span>256 / 256 cases matched</span></div></section><section class="overview-grid"><article class="panel dark-panel"><div class="panel-label">FLAGSHIP EXAMPLE <span>${badge("LIVE REFERENCE", "blue")}</span></div><h2>AgentApproval</h2><p class="muted">A bounded approval flow with explicit human and scope checks, compiled through the same generic GateX language path.</p>${compiled ? machineSummary(compiled) : "<div class=loading>Compiling proof artifact…</div>"}<div class="small-rule"></div><div class="state-line">${compiled ? compiled.compiled.machine.states.map((item) => `<span>${esc(item.name)}</span>`).join("<i>→</i>") : "IDLE → REQUESTED → APPROVED → USED"}</div></article><article class="panel source-panel"><div class="panel-label">SOURCE DSL <span>${badge("SOURCE VALID", "green")}</span></div>${sourceCard(AGENT_APPROVAL_SOURCE.trim())}<a class="text-link" href="#/workspace">Edit in workspace ↗</a></article></section><section class="proof-band"><div><span class="eyebrow">A SMALL, TRACEABLE LOOP</span><h2>From intent to a circuit you can inspect.</h2></div><div class="proof-grid">${proofStat("98", "NAND")}${proofStat("2", "LATCH")}${proofStat("100", "records")}${proofStat("2", "live circuits")}</div></section><section class="callout"><div class="callout-icon">◎</div><div><strong>Caller-owned state</strong><p>State is stored by this browser. TapeOut computes transitions; it does not store this workflow.</p></div></section></main>${footer()}`; }

function compilePanel(): string { const compiled = state.compiled; if (state.compiling) return `<section class="panel"><div class="loading">Compiling through the generic GateX path…</div></section>`; if (compiled === undefined) return `<section class="panel error-panel"><div class="panel-label">COMPILER DIAGNOSTICS ${badge("BLOCKED", "amber")}</div><div class="diagnostics">${state.diagnostics.map((item) => `<div class="diagnostic"><code>${esc(item.code)}</code><span>${esc(item.message)}</span><small>${esc(item.location)}</small></div>`).join("")}</div><p class="muted">Invalid source blocks manufacture readiness. Nothing is sent or signed from Gate F.</p></section>`; const expected = compiled.definition.expected; const sourceExact = state.source.trim() === compiled.definition.source.trim(); return `<section class="panel"><div class="panel-label">COMPILE RESULT <span>${badge("DETERMINISTIC", "green")}</span></div><div class="compile-head"><div><h3>${esc(compiled.definition.label)} <span class="id-chip">circuit ${compiled.definition.circuitId}</span></h3><p class="muted">Source valid. Generic parser, independent interpreter, canonical serializer.</p></div><span class="big-check">✓</span></div>${machineSummary(compiled)}<div class="kv-grid"><div><small>State encoding</small><code>${compiled.compiled.machine.stateBits} bits · LSB-first</code></div><div><small>Local container</small><code>${compiled.compiled.bytes.length} bytes · ${shortHash(compiled.compiled.hash)}</code></div><div><small>TapeOut payload</small><code>${compiled.payload.payload.length} bytes · ${shortHash(compiled.payload.payloadHash)}</code></div><div><small>Dimensions</small><code>(${compiled.payload.dimensions.nIn}, ${compiled.payload.dimensions.nOut}, ${compiled.payload.dimensions.nState}, ${compiled.payload.dimensions.gateCount})</code></div></div><div class="hash-line"><span>Local SHA-256</span><code>${esc(compiled.compiled.hash)}</code></div><div class="hash-line"><span>Payload SHA-256</span><code>${esc(compiled.payload.payloadHash)}</code></div><p class="compile-note">${sourceExact && compiled.artifactMatch && compiled.deterministic && compiled.compiled.bytes.length === expected.localBytes ? "Matches the accepted Gate E artifact." : "This source is valid but no longer bound to the accepted manufactured artifact."}</p></section>`; }
function verificationPanel(): string { const compiled = state.compiled; const sourceExact = compiled !== undefined && state.source.trim() === compiled.definition.source.trim(); const exact = compiled?.artifactMatch === true && compiled.deterministic && sourceExact; return `<section class="panel"><div class="panel-label">VERIFICATION CHAIN</div><div class="status-list">${statusRow("SOURCE VALID", compiled ? "passed" : "pending", compiled ? "Parser and validator accepted the current source." : "Waiting for valid source.")}${statusRow("COMPILE VERIFIED", exact ? "passed" : compiled ? "stale" : "pending", exact ? "Exact accepted artifact counts and hashes." : "Recompile after editing to restore the binding.")}${statusRow("EXHAUSTIVE FSM VERIFIED", exact ? "passed" : compiled ? "stale" : "pending", exact ? `${compiled?.definition.expected.cases ?? 0} encoded state/input cases in the accepted proof.` : "Proof is unavailable for changed source.")}${statusRow("MANUFACTURE CONFIRMED", exact ? "passed" : "stale", exact ? `Historical readback bound to circuit ${compiled?.definition.circuitId}.` : "Binding invalidated by source change.")}${statusRow("LIVE CHAIN MATCH", state.live && state.live.mismatches.length === 0 ? "passed" : "pending", state.live ? `${state.live.providers.length} providers at block ${state.live.block.number}.` : "Run a read-only live transition to compare.")}${statusRow("PROTOCOL SOURCE PROVENANCE UNRESOLVED", "warning", "Behavior is verified for the locked scope. Exact deployed source/build provenance remains unresolved.")}</div></section>`; }
function quotePanel(): string {
  const quote = state.quote;
  const quoteStale = quote !== undefined && state.live !== undefined && state.live.block.number > quote.block.number;
  const required = state.compiled?.compiled.nandCount ?? 0;
  const latch = state.compiled?.compiled.latchCount ?? 0;
  const nandDeficit = quote?.nandBalance === undefined ? undefined : BigInt(required) > quote.nandBalance ? BigInt(required) - quote.nandBalance : 0n;
  const latchDeficit = quote?.latchBalance === undefined ? undefined : BigInt(latch) > quote.latchBalance ? BigInt(latch) - quote.latchBalance : 0n;
  const mintTransactions = nandDeficit !== undefined && latchDeficit !== undefined ? (nandDeficit > 0n ? 1n : 0n) + (latchDeficit > 0n ? 1n : 0n) : undefined;
  const projectedValueWei = quote && nandDeficit !== undefined && latchDeficit !== undefined && mintTransactions !== undefined
    ? (nandDeficit + latchDeficit) * quote.mintPriceWei + mintTransactions * quote.protocolFeeWei + quote.tapeoutFeeWei
    : undefined;
  const insufficient = quote?.nativeBalanceWei !== undefined && projectedValueWei !== undefined && quote.nativeBalanceWei < projectedValueWei;
  const quoteBody = state.quoteLoading
    ? `<div class="loading">Reading both locked providers…</div>`
    : state.quoteError
      ? `<div class="inline-error"><strong>UNAVAILABLE</strong><span>${esc(state.quoteError)}</span></div>`
      : quote
        ? `<div class="quote-grid">${proofStat(quote.minted.toString(), "lifetime minted")}${proofStat(quote.cap.toString(), "shared cap")}${proofStat(`${weiToOkb(quote.mintPriceWei)} OKB`, "mint price / asset")}${proofStat(`${weiToOkb(quote.protocolFeeWei)} OKB`, "fixed mint fee / tx")}${proofStat(`${weiToOkb(quote.tapeoutFeeWei)} OKB`, "tapeout fee")}${proofStat(quote.nativeBalanceWei === undefined ? "unavailable" : `${weiToOkb(quote.nativeBalanceWei)} OKB`, "wallet balance")}${proofStat(projectedValueWei === undefined ? "unavailable" : `${weiToOkb(projectedValueWei)} OKB`, "projected value")}</div>${insufficient === true ? `<div class="inline-error"><strong>INSUFFICIENT OKB</strong><span>Chain balance is below the read-only manufacture quote.</span></div>` : ""}<div class="quote-meta"><span>${quoteStale ? "Quote is stale. Refresh before relying on it." : quote.agreement ? "Both locked providers agree" : "Provider disagreement"}</span><span>block ${quote.block.number} · ${esc(shortHash(quote.block.hash))}</span><span>gas price ${weiToOkb(quote.gasPriceWei)} OKB/OKB</span></div>`
        : `<p class="muted">Read current protocol getters from both locked providers. No wallet connection is requested.</p>`;
  const owned = quote?.nandBalance === undefined ? "unavailable" : `${quote.nandBalance} NAND · ${quote.latchBalance} LATCH`;
  const deficits = nandDeficit === undefined || latchDeficit === undefined ? "unavailable" : `${nandDeficit} NAND · ${latchDeficit} LATCH`;
  const quoteBadge = quoteStale ? badge("STALE", "amber") : badge(state.wallet.status === "ready" ? "ACCOUNT READ" : "NO WALLET", state.wallet.status === "ready" ? "blue" : "muted");
  return `<section class="panel quote-panel"><div class="panel-label">READ-ONLY QUOTE <span>${quoteBadge}</span></div><h3>Manufacture readiness</h3><p class="muted">Required inventory: <strong>${required}</strong> NAND · <strong>${latch}</strong> LATCH. Owned: <strong>${owned}</strong>. Deficit: <strong>${deficits}</strong>.</p>${quoteBody}<div class="quote-actions"><button class="button secondary" id="refresh-quote">Refresh locked quote</button><button class="button disabled" disabled>Manufacture disabled in Gate F</button></div><small class="safety-note">A quote is stale when its block or provider agreement is no longer current. Any future state-changing path must repeat exact sender simulation and integrity checks.</small></section>`;
}

function walletPanel(): string { const wallet = state.wallet; const detail = wallet.status === "ready" ? `${wallet.name ?? "OKX Wallet"} · ${abbreviatedAccount(wallet.account)} · X Layer / 196` : wallet.status === "wrong-network" ? `Wrong network ${wallet.chainId ?? "unknown"}. Switch manually before connecting.` : wallet.status === "unavailable" ? wallet.error ?? "OKX provider unavailable in this browser." : wallet.error ?? "No account connected."; const action = wallet.status === "ready" ? `<button class="button secondary small-button" id="disconnect-wallet">Disconnect</button>` : `<button class="button secondary small-button" id="connect-wallet" ${wallet.status === "unavailable" ? "disabled" : ""}>Connect OKX Wallet</button>`; return `<div class="wallet-state"><span class="status-icon ${wallet.status === "ready" ? "passed" : "warning"}">${wallet.status === "ready" ? "✓" : "•"}</span><span><strong>${wallet.status === "ready" ? "Wallet connected" : wallet.status === "wrong-network" ? "Wrong network" : "Wallet disconnected"}</strong><small>${esc(detail)}</small></span>${action}</div>`; }

function formatStateBytes(compiled: CompiledMachine, bytes: Uint8Array): string { const value = bytes.reduce((result, byte, index) => result | (byte << (index * 8)), 0); return stateName(compiled, value); }
function playground(): string { const compiled = state.compiled; if (compiled === undefined) return `<section class="panel muted-panel"><div class="panel-label">LIVE TRANSITION PLAYGROUND</div><p>Compile valid source to enable the comparison.</p></section>`; const machine = compiled.compiled.machine; const mask = machine.inputs.reduce((result, input, index) => result | (state.inputs[input.name] ? 1 << index : 0), 0); const local = localStep(compiled.compiled, state.selectedState, mask); const live = state.live; const inputControls = machine.inputs.map((input) => `<label class="toggle"><input type="checkbox" data-input="${esc(input.name)}" ${state.inputs[input.name] ? "checked" : ""}><span>${esc(input.name)}</span></label>`).join(""); return `<section class="panel playground"><div class="panel-label">LIVE TRANSITION PLAYGROUND <span>${badge("READ-ONLY", "blue")}</span></div><div class="play-head"><div><h3>Compare one transition</h3><p class="muted">Local AST result is always shown beside the live X Layer read. A live failure stays visible as unavailable.</p></div><button class="button primary small-button" id="run-live" ${state.liveLoading ? "disabled" : ""}>${state.liveLoading ? "Reading…" : "Run live read ↗"}</button></div><div class="play-controls"><label>Current state<select id="state-select">${machine.states.map((item, index) => `<option value="${index}" ${index === state.selectedState ? "selected" : ""}>${esc(item.name)} (${index})</option>`).join("")}</select></label><div><span class="control-label">Inputs</span><div class="toggles">${inputControls}</div></div></div><div class="comparison-grid"><div class="result-card local"><div class="result-label">LOCAL SIMULATION ${badge("AST INTERPRETER", "muted")}</div><strong>${esc(stateName(compiled.compiled, local.nextState))}</strong><div>output: ${local.outputs.map((value, index) => `${esc(machine.outputs[index]?.name ?? "output")}=${value ? "1" : "0"}`).join(" · ")}</div><code>next ${formatBytes(local.nextStateBytes)} · out ${formatBytes(local.outputBytes)}</code></div><div class="result-card live"><div class="result-label">LIVE X LAYER ${badge(live ? (live.mismatches.length === 0 ? "MATCH" : "MISMATCH") : "UNAVAILABLE", live && live.mismatches.length === 0 ? "green" : "amber")}</div>${live ? `<strong>${esc(formatStateBytes(compiled.compiled, live.nextState))}</strong><div>output: ${esc(formatBytes(live.outputs))}</div><code>block ${live.block.number} · ${esc(shortHash(live.block.hash))}</code>${live.mismatches.length > 0 ? `<div class="inline-error">${live.mismatches.map(esc).join(" ")}</div>` : ""}` : `<strong>Not read yet</strong><div>Run the locked two-provider read-only check.</div><code>${state.liveError ? esc(state.liveError) : "No fallback to local result"}</code>`}</div></div><div class="provider-line">${live ? `Providers: ${live.providers.map(esc).join(" · ")} · common block ${live.block.number}` : "No live result recorded"}</div></section>`; }
function workspace(): string { const compiled = state.compiled; const selected = state.key === "agent" ? "AgentApproval" : "TinyApproval"; const restored = state.restored ? `<p class="local-history"><strong>LOCAL</strong> Restored history for circuit ${esc(state.restored.circuitId)}. It is not fresh live evidence.</p>` : ""; return `${nav("/workspace")}<main class="page workspace"><section class="page-heading"><div><div class="eyebrow">WORKSPACE / GATE F</div><h1>Compile. Inspect. Compare.</h1><p>One bounded authoring loop from DSL to independently checked live transition.</p></div>${walletPanel()}</section><div class="example-tabs"><button class="tab ${selected === "AgentApproval" ? "active" : ""}" data-example="agent">AgentApproval <small>circuit 2</small></button><button class="tab ${selected === "TinyApproval" ? "active" : ""}" data-example="tiny">TinyApproval <small>circuit 1</small></button></div><section class="workspace-grid"><div class="workspace-main"><section class="panel editor-panel"><div class="panel-label">DSL SOURCE <span>${badge(compiled ? "EDITABLE" : "DIAGNOSTICS", compiled ? "blue" : "amber")}</span></div><textarea id="source-editor" spellcheck="false" aria-label="GateX DSL source">${esc(state.source)}</textarea><div class="editor-foot"><span>Generic GateX language · reset priority · transition-pulse outputs</span><button class="button secondary small-button" id="reset-source">Restore locked example</button></div></section>${compilePanel()}${playground()}</div><aside class="workspace-side">${verificationPanel()}<section class="panel"><div class="panel-label">STATE MACHINE</div>${compiled ? stateDiagram(compiled.compiled) : `<p class="muted">State diagram waits for valid source.</p>`}</section>${quotePanel()}<section class="panel disclosure"><div class="panel-label">SESSION STORAGE</div><p>State is stored by this browser. TapeOut computes transitions; it does not store this workflow.</p>${restored}<p class="muted">Restored histories are labeled LOCAL, never fresh live evidence. A source change invalidates the circuit binding.</p></section></aside></section></main>${footer()}`; }

function artifactEvidence(counts: string, bytes: string, localSha: string, payloadSha: string, cases: string): string { return `<div class="artifact-list"><div><span>${esc(counts)}</span><strong>${esc(cases)}</strong></div><div><span>${esc(bytes)}</span><small>dimensions recorded in readback</small></div><div><small>local SHA-256</small><code>${esc(localSha)}</code></div><div><small>TapeOut payload SHA-256</small><code>${esc(payloadSha)}</code></div></div>`; }
function evidence(): string { return `${nav("/evidence")}<main class="page evidence"><section class="page-heading"><div><div class="eyebrow">EVIDENCE / READ-ONLY RECORD</div><h1>What has been proven.</h1><p>Historical manufacture and live comparison remain distinct from the browser session and from future wallet actions.</p></div>${badge("GATE E ACCEPTED", "green")}</section><section class="evidence-hero panel dark-panel"><div><div class="panel-label">CANONICAL GATEX DEPLOYMENT</div><h2>Two real circuits. One locked boundary.</h2><p class="muted">Processor <code>${browserDeployment.processor}</code><br>Token <code>${browserDeployment.token}</code><br>Chain ${browserDeployment.chainId} · registry index ${browserDeployment.registryIndex}</p></div><div class="evidence-count">${proofStat("512", "live comparisons")}${proofStat("0", "mismatches")}</div></section><div class="evidence-grid"><article class="panel evidence-card"><div class="panel-label">TINYAPPROVAL <span>${badge("HISTORICAL EVIDENCE", "muted")}</span></div><h2>circuit 1</h2><p class="muted">LOCKED → READY → USED</p>${artifactEvidence("89 NAND · 2 LATCH · 91 records", "643 bytes local · 631 bytes TapeOut", "adee32d4133073926d312a711643d16ac7d849c7e662c2bce8f6131c35fd0334", "7ec1ed9fe2e0c5f92a45b2ad49fe3da969c109f01522d8306fe127aba76cabac", "32 / 32 cases")}</article><article class="panel evidence-card featured"><div class="panel-label">AGENTAPPROVAL <span>${badge("LIVE X LAYER", "blue")}</span></div><h2>circuit 2</h2><p class="muted">IDLE → REQUESTED → APPROVED → USED</p>${artifactEvidence("98 NAND · 2 LATCH · 100 records", "706 bytes local · 694 bytes TapeOut", "d68c9881fbe8bf0fbf7f86cfa92ad2889389e07e09bb0e7f0068f23eded50003", "7e4b5f83032beaf32ce2e7c067f1ee24d08feea1e2db8c64ef7c4d7de231dc45", "256 / 256 cases matched")}</article></div><section class="panel history-panel"><div class="panel-label">MANUFACTURE RECORD</div><div class="history-grid"><div><small>Manufacture tx</small><a href="https://www.oklink.com/xlayer/tx/0xf8fca87f75de3ebf9326071b0341c9307dd5d768c90558542c6013100816a8be" target="_blank" rel="noreferrer">0xf8fca87f…0816a8be ↗</a></div><div><small>Block</small><code>72528952 · 0x13356c8f…</code></div><div><small>Dimensions</small><code>(6, 1, 2, 100)</code></div><div><small>Live evidence</small><code>2 providers · block 72529601</code></div></div><p class="limitation">PROTOCOL SOURCE PROVENANCE UNRESOLVED. Runtime behavior is verified for the recorded scope. This does not establish exact deployed-source verification, immutability, authoritative workflow state, custody, or replay-proof approvals.</p></section><section class="callout"><div class="callout-icon">◎</div><div><strong>Historical evidence stays historical.</strong><p>Restored browser sessions are labeled LOCAL. Only a fresh read against both locked providers can earn the LIVE X LAYER label.</p></div></section></main>${footer()}`; }
function footer(): string { return `<footer><span>GateX / Gate F</span><span>Read-only product verification · caller-owned state</span></footer>`; }
function render(): void { if (app) { app.innerHTML = route() === "/" ? landing() : route() === "/workspace" ? workspace() : evidence(); bindEvents(); } }

function bindEvents(): void {
  document.querySelectorAll<HTMLButtonElement>("[data-example]").forEach((button) => button.addEventListener("click", () => { const key = button.dataset.example as ExampleKey; state.key = key; state.source = EXAMPLES[key].source; state.compiled = undefined; state.restored = undefined; state.quote = undefined; state.quoteError = undefined; void compileCurrent(); }));
  const editor = document.querySelector<HTMLTextAreaElement>("#source-editor");
  editor?.addEventListener("input", () => { state.source = editor.value; state.compiled = undefined; state.restored = undefined; state.quote = undefined; state.quoteError = undefined; state.diagnostics = []; window.clearTimeout(compileTimer); compileTimer = window.setTimeout(() => void compileCurrent(), 350); });
  document.querySelector<HTMLButtonElement>("#reset-source")?.addEventListener("click", () => { state.source = EXAMPLES[state.key].source; state.quote = undefined; state.quoteError = undefined; void compileCurrent(); });
  document.querySelector<HTMLButtonElement>("#refresh-quote")?.addEventListener("click", () => void refreshQuote());
  document.querySelector<HTMLButtonElement>("#connect-wallet")?.addEventListener("click", () => void connectWallet());
  document.querySelector<HTMLButtonElement>("#disconnect-wallet")?.addEventListener("click", () => { state.wallet = { ...state.wallet, status: "disconnected", account: undefined, error: undefined }; state.quote = undefined; render(); });
  document.querySelector<HTMLSelectElement>("#state-select")?.addEventListener("change", (event) => { state.selectedState = Number((event.target as HTMLSelectElement).value); state.live = undefined; state.liveError = undefined; render(); });
  document.querySelectorAll<HTMLInputElement>("[data-input]").forEach((input) => input.addEventListener("change", () => { const name = input.dataset.input; if (name) state.inputs[name] = input.checked; state.live = undefined; state.liveError = undefined; render(); }));
  document.querySelector<HTMLButtonElement>("#run-live")?.addEventListener("click", () => void runLive());
}
let compileTimer = 0;
async function refreshQuote(): Promise<void> { state.quoteLoading = true; state.quoteError = undefined; render(); try { state.quote = await readOnlyQuote(state.wallet.account); } catch (error) { state.quote = undefined; state.quoteError = error instanceof Error ? error.message : String(error); } finally { state.quoteLoading = false; render(); } }
async function connectWallet(): Promise<void> { state.wallet = await requestOkxAccounts(state.wallet); if (state.wallet.status === "ready") { try { state.quote = await readOnlyQuote(state.wallet.account); } catch (error) { state.quote = undefined; state.quoteError = error instanceof Error ? error.message : String(error); } } render(); }
async function runLive(): Promise<void> { if (state.compiled === undefined) return; state.liveLoading = true; state.liveError = undefined; render(); try { const machine = state.compiled.compiled.machine; const mask = machine.inputs.reduce((result, input, index) => result | (state.inputs[input.name] ? 1 << index : 0), 0); state.live = await readLiveStep(state.compiled.definition.circuitId, new Uint8Array([state.selectedState]), inputBytes(state.compiled.compiled, state.inputs)); const local = localStep(state.compiled.compiled, state.selectedState, mask); const localState = formatStateBytes(state.compiled.compiled, local.nextStateBytes); const liveState = formatStateBytes(state.compiled.compiled, state.live.nextState); const localOutput = formatBytes(local.outputBytes); const liveOutput = formatBytes(state.live.outputs); if (localState !== liveState || localOutput !== liveOutput) state.live.mismatches.push(`AST/local mismatch: local ${localState}/${localOutput}, live ${liveState}/${liveOutput}`); const session: BrowserSession = { artifactDigest: state.compiled.compiled.hash, chainId: browserLock.chainId, processor: browserDeployment.processor, circuitId: state.compiled.definition.circuitId, sourceDigest: state.compiled.sourceDigest, activeState: liveState, history: [{ state: stateName(state.compiled.compiled, state.selectedState), inputs: { ...state.inputs }, localNext: localState, localOutput, origin: "LIVE X LAYER", recordedAt: new Date().toISOString() }] }; upsertSession(session); state.restored = session; } catch (error) { state.live = undefined; state.liveError = error instanceof Error ? error.message : String(error); } finally { state.liveLoading = false; render(); } }
async function boot(root: HTMLElement): Promise<void> {
  root.innerHTML = `${nav("/")}<main class="page loading-page"><div class="loading">Loading locked artifacts…</div></main>`;
  installEip6963Discovery();
  state.wallet = await readWallet(discoverOkxProvider());
  bindProviderEvents(state.wallet, (next) => { state.wallet = next; state.quote = undefined; state.quoteError = "Wallet/account/network changed. Readiness was invalidated."; render(); });
  window.addEventListener("hashchange", () => { render(); });
  render();
  const watchdog = window.setTimeout(() => {
    if (state.compiling) {
      state.compiling = false;
      state.diagnostics = [{ code: "BROWSER_RUNTIME", message: "The browser compiler did not settle. The UI remains read-only and manufacture-disabled.", location: "runtime" }];
      render();
    }
  }, 5000);
  try { state.compiled = await compileExample("agent"); state.inputs = Object.fromEntries(state.compiled.compiled.machine.inputs.map((input) => [input.name, false])); const restored = readSessions().find((candidate) => sessionKey(candidate) === sessionKey({ artifactDigest: state.compiled?.compiled.hash ?? "", chainId: browserLock.chainId, processor: browserDeployment.processor, circuitId: state.compiled?.definition.circuitId ?? "" }) && candidate.sourceDigest === state.compiled?.sourceDigest); state.restored = restored === undefined ? undefined : { ...restored, history: restored.history.map((entry) => ({ ...entry, origin: "LOCAL SIMULATION" as const })) }; }
  catch (error) { state.diagnostics = diagnosticFromError(error, state.source); }
  finally { window.clearTimeout(watchdog); }
  state.compiling = false;
  render();
}

export { compileMachine, readSessions, sessionKey };
